// Seed data extracted from Matiasさん.pdf — Minna no Nihongo lessons with Shinako sensei
// Covers June–September lessons

export const SEED_LESSONS = [
  {
    order: 1, unit: 1, unitName: 'Getting Started',
    title: 'Introducing Yourself', titleJp: 'じこしょうかい', emoji: '👋',
    xpRequired: 0, xpReward: 80,
    challenges: [
      { type:'mc-jp-en', prompt:'What does this mean?', jp:'わたし', romaji:'watashi', options:['I / me','you','he / she','we'], answer:'I / me' },
      { type:'fill', prompt:'Complete the sentence (topic marker):', sentence:['わたし','___','マティアスです。'], options:['は','を','に','で'], answer:'は', hint:'は (wa) marks the topic of the sentence' },
      { type:'tap', prompt:'Build: "I am a student."', answer:['わたしは','がくせいです。'], bank:['わたしは','がくせいです。','せんせいです。','あなたは'] },
      { type:'mc-jp-en', prompt:'What does this sentence mean?', jp:'せんせいじゃありません。', romaji:'sensei ja arimasen', options:['I am a teacher','I am not a teacher','Are you a teacher?','He is a teacher'], answer:'I am not a teacher' },
      { type:'mc-en-jp', prompt:'How do you say "Are you a student?"', options:['がくせいですか？','わたしはがくせいです。','せんせいですか？','がくせいじゃありません。'], romaji:['gakusei desu ka','watashi wa gakusei desu','sensei desu ka','gakusei ja arimasen'], answer:'がくせいですか？' },
      { type:'tap', prompt:'Build: "I am also Argentine."', answer:['わたしも','アルゼンチンじんです。'], bank:['わたしも','アルゼンチンじんです。','わたしは','かんこくじんです。','アルゼンチンじんですか？'] },
    ],
  },
  {
    order: 2, unit: 1, unitName: 'Getting Started',
    title: 'の & も Particles', titleJp: 'の と も', emoji: '🔗',
    xpRequired: 80, xpReward: 80,
    challenges: [
      { type:'mc-jp-en', prompt:'What does の do in "エンジニアのしごと"?', jp:'エンジニアのしごと', romaji:'enjinia no shigoto', options:['Object marker','Connects two nouns (possession/type)','Topic marker','Direction marker'], answer:'Connects two nouns (possession/type)' },
      { type:'fill', prompt:'Fill the blank (possession):', sentence:['これは','わたし','___','ほんです。'], options:['の','は','も','を'], answer:'の', hint:'の connects nouns — "my book"' },
      { type:'mc-jp-en', prompt:'What does も mean here?', jp:'わたしも エンジニアです。', romaji:'watashi mo enjinia desu', options:['I am not an engineer','I am an engineer (also, same as others)','Are you an engineer?','I am only an engineer'], answer:'I am an engineer (also, same as others)' },
      { type:'tap', prompt:'Build: "This is a Japanese-language book."', answer:['これは','にほんごの','ほんです。'], bank:['これは','にほんごの','ほんです。','えいごの','なんの'] },
      { type:'mc-en-jp', prompt:'"What kind of book is that?"', options:['それは なんのほん ですか？','それは なんですか？','それは どこのほん ですか？','なんのほん ありますか？'], romaji:['sore wa nanno hon desu ka','sore wa nan desu ka','sore wa doko no hon desu ka','nanno hon arimasu ka'], answer:'それは なんのほん ですか？' },
    ],
  },
  {
    order: 3, unit: 1, unitName: 'Getting Started',
    title: 'Demonstratives', titleJp: 'これ・それ・あれ', emoji: '👆',
    xpRequired: 160, xpReward: 80,
    challenges: [
      { type:'mc-jp-en', prompt:'Something close to YOU:', jp:'これ', romaji:'kore', options:['This (near me)','That (near you)','That (over there)','Which one?'], answer:'This (near me)' },
      { type:'mc-jp-en', prompt:'Something near the listener:', jp:'それ', romaji:'sore', options:['This (near me)','That (near you)','That (over there)','Here'], answer:'That (near you)' },
      { type:'fill', prompt:'Fill the blank:', sentence:['___','は','なんですか？'], options:['これ','どこ','だれ','いつ'], answer:'これ', hint:'You\'re asking about something close to you' },
      { type:'tap', prompt:'Build: "What is that over there?"', answer:['あれは','なんですか？'], bank:['あれは','なんですか？','これは','それは','どこですか？'] },
      { type:'mc-en-jp', prompt:'"That (near you) is a menu."', options:['それは メニューです。','これは メニューです。','あれは メニューです。','どれは メニューですか？'], romaji:['sore wa menyuu desu','kore wa menyuu desu','are wa menyuu desu','dore wa menyuu desu ka'], answer:'それは メニューです。' },
    ],
  },
  {
    order: 4, unit: 2, unitName: 'Getting Around',
    title: 'Locations: ここ・そこ・あそこ', titleJp: 'ばしょ', emoji: '📍',
    xpRequired: 240, xpReward: 90,
    challenges: [
      { type:'mc-jp-en', prompt:'Location near the speaker:', jp:'ここ', romaji:'koko', options:['Here (near me)','There (near you)','Over there','Where?'], answer:'Here (near me)' },
      { type:'mc-jp-en', prompt:'How do you ask where something is?', jp:'トイレは どこですか？', romaji:'toire wa doko desu ka', options:['Where is the bathroom?','What is the bathroom?','Is there a bathroom?','How much is the bathroom?'], answer:'Where is the bathroom?' },
      { type:'fill', prompt:'Fill the blank:', sentence:['___','は','こうえんです。'], options:['あそこ','だれ','いくら','なに'], answer:'あそこ', hint:'Something over there (away from both speakers)' },
      { type:'tap', prompt:'Build: "The convenience store is there (near you)."', answer:['そこは','コンビニです。'], bank:['そこは','コンビニです。','ここは','あそこは','コンビニですか？'] },
      { type:'mc-en-jp', prompt:'"Where is the station?"', options:['えきは どこですか？','えきは なんですか？','えきは いくらですか？','えきに いきます。'], romaji:['eki wa doko desu ka','eki wa nan desu ka','eki wa ikura desu ka','eki ni ikimasu'], answer:'えきは どこですか？' },
      { type:'mc-jp-en', prompt:'Meaning of ちかてつ:', jp:'ちかてつ (地下鉄)', romaji:'chikatetsu', options:['Airplane','Subway / Metro','Bus','Train'], answer:'Subway / Metro' },
    ],
  },
  {
    order: 5, unit: 2, unitName: 'Getting Around',
    title: 'Possessives & だれの', titleJp: 'だれのですか', emoji: '🎒',
    xpRequired: 330, xpReward: 90,
    challenges: [
      { type:'mc-jp-en', prompt:'What does だれの mean?', jp:'だれの', romaji:'dare no', options:["Whose","Where","When","Who"], answer:'Whose' },
      { type:'tap', prompt:'Build: "Whose bag is this?"', answer:['これは','だれの','かばんですか？'], bank:['これは','だれの','かばんですか？','それは','どこの'] },
      { type:'fill', prompt:'Fill the blank:', sentence:['これは','___','かばんです。'], options:['わたしの','わたしは','わたしを','わたしに'], answer:'わたしの', hint:'Use の to show possession' },
      { type:'mc-en-jp', prompt:'"This is Shinako-sensei\'s notebook."', options:['これは しなこせんせいの ノートです。','これは しなこせんせいは ノートです。','しなこせんせいは このノートですか？','それは しなこせんせいの ノートですか？'], romaji:['kore wa shinako sensei no noto desu','kore wa shinako sensei wa noto desu','shinako sensei wa kono noto desu ka','sore wa shinako sensei no noto desu ka'], answer:'これは しなこせんせいの ノートです。' },
    ],
  },
  {
    order: 6, unit: 3, unitName: 'Daily Routines',
    title: 'Daily Verbs', titleJp: 'どうし', emoji: '⏰',
    xpRequired: 420, xpReward: 100,
    challenges: [
      { type:'mc-jp-en', prompt:'What does this verb mean?', jp:'おきます', romaji:'okimasu', options:['Wake up','Sleep','Eat','Work'], answer:'Wake up' },
      { type:'mc-jp-en', prompt:'What does this verb mean?', jp:'はたらきます', romaji:'hatarakimasu', options:['Study','Work','Rest','Exercise'], answer:'Work' },
      { type:'fill', prompt:'Choose the right particle (object):', sentence:['ごはんを','___','います。'], options:['たべて','のんで','いって','きて'], answer:'たべて', hint:'ごはんを = object marker; the verb root should follow' },
      { type:'tap', prompt:'Build: "I go to school by bus."', answer:['バスで','がっこうに','いきます。'], bank:['バスで','がっこうに','いきます。','でんしゃで','たべます。','きます。'] },
      { type:'mc-jp-en', prompt:'Past tense of いきます:', jp:'いきました', romaji:'ikimashita', options:['I go','I went','I will go','I don\'t go'], answer:'I went' },
      { type:'mc-en-jp', prompt:'"I did not exercise yesterday."', options:['きのう、うんどうしませんでした。','きのう、うんどうしました。','まいにち、うんどうしています。','きのう、うんどうします。'], romaji:['kinou, undou shimasen deshita','kinou, undou shimashita','mainichi, undou shiteimasu','kinou, undou shimasu'], answer:'きのう、うんどうしませんでした。' },
    ],
  },
  {
    order: 7, unit: 3, unitName: 'Daily Routines',
    title: 'Time & Schedule', titleJp: 'じかん と スケジュール', emoji: '🕘',
    xpRequired: 520, xpReward: 100,
    challenges: [
      { type:'mc-jp-en', prompt:'What does から〜まで express?', jp:'９じから６じまで', romaji:'kuji kara rokuji made', options:['At 9 and at 6','From 9 to 6','Before 9, after 6','Around 9 or 6'], answer:'From 9 to 6' },
      { type:'tap', prompt:'Build: "I work from 9am to 6pm."', answer:['ごぜん９じから','ごご６じまで','はたらきます。'], bank:['ごぜん９じから','ごご６じまで','はたらきます。','べんきょうします。','７じから'] },
      { type:'fill', prompt:'Fill the blank (duration particle):', sentence:['６じ','___','８じまで うんどうしました。'], options:['から','まで','に','で'], answer:'から', hint:'から = from (a starting point)' },
      { type:'mc-en-jp', prompt:'"What time do you work from?"', options:['なんじから しごとですか？','なんじに しごとですか？','なんじまで しごとですか？','なんじ しごとします？'], romaji:['nanji kara shigoto desu ka','nanji ni shigoto desu ka','nanji made shigoto desu ka','nanji shigoto shimasu'], answer:'なんじから しごとですか？' },
      { type:'mc-jp-en', prompt:'What does さいきん mean?', jp:'さいきん (最近)', romaji:'saikin', options:['Recently / lately','Every day','Next week','A long time ago'], answer:'Recently / lately' },
      { type:'mc-jp-en', prompt:'What does 週末 mean?', jp:'しゅうまつ (週末)', romaji:'shuumatsu', options:['Weekday','Weekend','Next week','Every week'], answer:'Weekend' },
    ],
  },
  {
    order: 8, unit: 3, unitName: 'Daily Routines',
    title: 'い-Adjective Past Tense', titleJp: 'けいようし かこ', emoji: '🌡️',
    xpRequired: 620, xpReward: 100,
    challenges: [
      { type:'mc-jp-en', prompt:'Past tense of さむい:', jp:'さむかったです', romaji:'samukatta desu', options:['It is cold','It was cold','It is not cold','It will be cold'], answer:'It was cold' },
      { type:'fill', prompt:'Form the past tense (drop い → add かった):', sentence:['おいしい','→','おいし','___','です。'], options:['かった','いた','った','なかった'], answer:'かった', hint:'い-adjectives: drop い → add かった' },
      { type:'tap', prompt:'Build: "This morning was very cold."', answer:['けさは','とても','さむかったです。'], bank:['けさは','とても','さむかったです。','あつかったです。','きのうは'] },
      { type:'mc-en-jp', prompt:'"The food at that convenience store was delicious."', options:['あのコンビニのごはんは おいしかったです。','あのコンビニのごはんは おいしいです。','このごはんは おいしくないです。','コンビニのごはんは なんですか？'], romaji:['ano konbini no gohan wa oishikatta desu','ano konbini no gohan wa oishii desu','kono gohan wa oishikunai desu','konbini no gohan wa nan desu ka'], answer:'あのコンビニのごはんは おいしかったです。' },
      { type:'mc-jp-en', prompt:'Meaning:', jp:'とても', romaji:'totemo', options:['A little','Very','About / approximately','Recently'], answer:'Very' },
      { type:'mc-jp-en', prompt:'Meaning:', jp:'だいたい', romaji:'daitai', options:['Exactly','Very','About / approximately','Always'], answer:'About / approximately' },
    ],
  },
  {
    order: 9, unit: 4, unitName: 'Natural Japanese',
    title: '〜ています (te-form)', titleJp: 'ています', emoji: '🔄',
    xpRequired: 720, xpReward: 110,
    challenges: [
      { type:'mc-jp-en', prompt:'What does this express?', jp:'いま、ごはんをたべています。', romaji:'ima, gohan wo tabeteimasu', options:['I ate rice','I am eating rice right now','I will eat rice','I eat rice every day'], answer:'I am eating rice right now' },
      { type:'mc-jp-en', prompt:'What does this express?', jp:'わたしは けっこんしています。', romaji:'watashi wa kekkon shiteimasu', options:['I got married (past, one-time)','I am (currently) married','I want to get married','I am not married'], answer:'I am (currently) married' },
      { type:'tap', prompt:'Build: "I study Japanese every day." (habit)', answer:['まいにち、','にほんごを','べんきょうしています。'], bank:['まいにち、','にほんごを','べんきょうしています。','べんきょうしました。','えいごを','ときどき'] },
      { type:'mc-en-jp', prompt:'"He works in Tokyo."', options:['かれは とうきょうで はたらいています。','かれは とうきょうに はたらきました。','かれは とうきょうへ いきます。','かれは とうきょうが すきです。'], romaji:['kare wa toukyou de hataraiteimasu','kare wa toukyou ni hatarakimashita','kare wa toukyou e ikimasu','kare wa toukyou ga suki desu'], answer:'かれは とうきょうで はたらいています。' },
      { type:'fill', prompt:'Fill the blank (ongoing action):', sentence:['３ねんかん、にほんごを','べんきょうして','___','。'], options:['います','いました','いきます','きます'], answer:'います', hint:'〜ています = action continuing until now' },
    ],
  },
  {
    order: 10, unit: 4, unitName: 'Natural Japanese',
    title: 'Transport & Travel', titleJp: 'のりもの と たび', emoji: '✈️',
    xpRequired: 830, xpReward: 110,
    challenges: [
      { type:'mc-jp-en', prompt:'What does this word mean?', jp:'ひこうき', romaji:'hikouki', options:['Airplane','Train','Subway','Bus'], answer:'Airplane' },
      { type:'mc-jp-en', prompt:'What does this word mean?', jp:'ちかてつ (地下鉄)', romaji:'chikatetsu', options:['Airport','Subway','Bullet train','Taxi'], answer:'Subway' },
      { type:'fill', prompt:'Means of transport particle:', sentence:['でんしゃ','___','とうきょうに いきます。'], options:['で','を','に','が'], answer:'で', hint:'で = by means of (transport, tool, method)' },
      { type:'tap', prompt:'Build: "Can I pay by card?"', answer:['クレジットカードで','はらえますか？'], bank:['クレジットカードで','はらえますか？','げんきんで','いくらですか？','つかえますか？'] },
      { type:'mc-en-jp', prompt:'"I went to the park by subway last Sunday."', options:['せんしゅうの にちようびに、ちかてつで こうえんに いきました。','せんしゅうの にちようびに、でんしゃで こうえんへ いきます。','こうえんに ちかてつが あります。','にちようびに こうえんで ちかてつに のります。'], romaji:['senshuu no nichiyoubi ni, chikatetsu de kouen ni ikimashita','senshuu no nichiyoubi ni, densha de kouen e ikimasu','kouen ni chikatetsu ga arimasu','nichiyoubi ni kouen de chikatetsu ni norimasu'], answer:'せんしゅうの にちようびに、ちかてつで こうえんに いきました。' },
    ],
  },
  {
    order: 11, unit: 4, unitName: 'Natural Japanese',
    title: 'Birthdays & Dates', titleJp: 'たんじょうびと ひづけ', emoji: '🎂',
    xpRequired: 940, xpReward: 110,
    challenges: [
      { type:'mc-jp-en', prompt:'What does this mean?', jp:'たんじょうび', romaji:'tanjoubi', options:['New Year','Birthday','Holiday','Anniversary'], answer:'Birthday' },
      { type:'mc-jp-en', prompt:'How do you read ６月？', jp:'６月', romaji:'rokugatsu', options:['gogatsu','rokugatsu','shichigatsu','hachigatsu'], answer:'rokugatsu' },
      { type:'tap', prompt:'Build: "My birthday is January 7th."', answer:['わたしのたんじょうびは','１がつ７か（なのか）です。'], bank:['わたしのたんじょうびは','１がつ７か（なのか）です。','６がつです。','たんじょうびは なんですか？'] },
      { type:'fill', prompt:'Fill the blank (irregular date reading):', sentence:['１がつ','___','（ついたち）は、おしょうがつです。'], options:['１にち','ひとつ','いちにち','つき'], answer:'１にち', hint:'The 1st is read ついたち — shown here as １にち for input' },
      { type:'mc-jp-en', prompt:'What does 〜間（かん）express?', jp:'１しゅうかん', romaji:'isshuukan', options:['One week (point in time)','For one week (duration)','Every week','Last week'], answer:'For one week (duration)' },
    ],
  },
  {
    order: 12, unit: 5, unitName: 'Real-Life Japanese',
    title: 'At the Restaurant', titleJp: 'レストランで', emoji: '🍜',
    xpRequired: 1050, xpReward: 120,
    challenges: [
      { type:'mc-jp-en', prompt:'What do staff say when you enter?', jp:'いらっしゃいませ', romaji:'irasshaimase', options:['Welcome!','How many people?','Here is your menu.','Thank you!'], answer:'Welcome!' },
      { type:'tap', prompt:'Build: "One draft beer and one ramen, please."', answer:['なまビールと','ラーメンを','ひとつずつ','おねがいします。'], bank:['なまビールと','ラーメンを','ひとつずつ','おねがいします。','ふたつ','ください。'] },
      { type:'mc-en-jp', prompt:'"What do you recommend?"', options:['おすすめは なんですか？','これは なんですか？','メニューを ください。','おかいけいを おねがいします。'], romaji:['osusume wa nan desu ka','kore wa nan desu ka','menyuu wo kudasai','okaikei wo onegaishimasu'], answer:'おすすめは なんですか？' },
      { type:'fill', prompt:'Fill the blank:', sentence:['おかいけいを','___','します。'], options:['おねがい','どうぞ','ありがとう','すみません'], answer:'おねがい', hint:'おかいけいをおねがいします = the bill please' },
      { type:'mc-jp-en', prompt:'Said after finishing your meal:', jp:'ごちそうさまでした', romaji:'gochisousama deshita', options:['Let\'s eat!','Thank you for the meal (after eating)','Excuse me!','Welcome!'], answer:'Thank you for the meal (after eating)' },
      { type:'tap', prompt:'Build: "Certainly. Please wait a moment."', answer:['かしこまりました。','しょうしょう','おまちください。'], bank:['かしこまりました。','しょうしょう','おまちください。','ありがとうございます。','おまたせいたしました。'] },
    ],
  },
  {
    order: 13, unit: 5, unitName: 'Real-Life Japanese',
    title: 'Food Vocabulary', titleJp: 'たべもの と のみもの', emoji: '🐟',
    xpRequired: 1170, xpReward: 120,
    challenges: [
      { type:'mc-jp-en', prompt:'Type of meat:', jp:'ぶたにく (豚肉)', romaji:'butaniku', options:['Beef','Pork','Chicken','Lamb'], answer:'Pork' },
      { type:'mc-jp-en', prompt:'Type of seafood:', jp:'まぐろ (鮪)', romaji:'maguro', options:['Salmon','Octopus','Tuna','Shrimp'], answer:'Tuna' },
      { type:'mc-jp-en', prompt:'What is a 定食 (ていしょく)?', jp:'ていしょく (定食)', romaji:'teishoku', options:['A set meal with rice, main dish, miso soup','Just rice','A bowl with toppings','A buffet'], answer:'A set meal with rice, main dish, miso soup' },
      { type:'mc-jp-en', prompt:'What does 〇〇丼 (どん) mean?', jp:'〇〇丼', romaji:'__ don', options:['Stir-fry dish','Simmered dish','Deep rice bowl with toppings','Set meal'], answer:'Deep rice bowl with toppings' },
      { type:'mc-en-jp', prompt:'"I can\'t eat pork because I\'m allergic."', options:['ぶたにくは アレルギーで たべられません。','ぶたにくを たべません。','ぶたにくが きらいです。','ぶたにくは ありません。'], romaji:['butaniku wa arerugii de taberaremasen','butaniku wo tabemasen','butaniku ga kirai desu','butaniku wa arimasen'], answer:'ぶたにくは アレルギーで たべられません。' },
      { type:'fill', prompt:'Fill the blank (all-you-can-drink):', sentence:['___','ほうだい','で のめます。'], options:['のみ','たべ','かい','やすみ'], answer:'のみ', hint:'のみほうだい = all-you-can-drink' },
    ],
  },
]

export const SEED_VOCAB = [
  // Unit 1 — Basics
  { packLabel:'Basics', xpRequired:0, jp:'わたし', romaji:'watashi', en:'I / me', kanji:'私', kanjiDifficulty:'N5' },
  { packLabel:'Basics', xpRequired:0, jp:'あなた', romaji:'anata', en:'you' },
  { packLabel:'Basics', xpRequired:0, jp:'です', romaji:'desu', en:'is / am / are (polite)' },
  { packLabel:'Basics', xpRequired:0, jp:'じゃありません', romaji:'ja arimasen', en:'is not (polite negative)' },
  { packLabel:'Basics', xpRequired:0, jp:'ですか', romaji:'desu ka', en:'is it? (question marker)' },
  { packLabel:'Basics', xpRequired:0, jp:'も', romaji:'mo', en:'also / too' },
  { packLabel:'Basics', xpRequired:0, jp:'の', romaji:'no', en:'possessive / noun connector' },
  { packLabel:'Basics', xpRequired:0, jp:'は', romaji:'wa', en:'topic marker' },
  { packLabel:'Basics', xpRequired:0, jp:'がくせい', romaji:'gakusei', en:'student', kanji:'学生', kanjiDifficulty:'N5' },
  { packLabel:'Basics', xpRequired:0, jp:'せんせい', romaji:'sensei', en:'teacher', kanji:'先生', kanjiDifficulty:'N5' },
  { packLabel:'Basics', xpRequired:0, jp:'エンジニア', romaji:'enjinia', en:'engineer' },
  { packLabel:'Basics', xpRequired:0, jp:'アルゼンチンじん', romaji:'aruzentinjin', en:'Argentine (person)' },

  // Unit 2 — Places
  { packLabel:'Places & Things', xpRequired:240, jp:'ここ', romaji:'koko', en:'here (near me)' },
  { packLabel:'Places & Things', xpRequired:240, jp:'そこ', romaji:'soko', en:'there (near you)' },
  { packLabel:'Places & Things', xpRequired:240, jp:'あそこ', romaji:'asoko', en:'over there' },
  { packLabel:'Places & Things', xpRequired:240, jp:'どこ', romaji:'doko', en:'where?' },
  { packLabel:'Places & Things', xpRequired:240, jp:'えき', romaji:'eki', en:'station', kanji:'駅', kanjiDifficulty:'N5' },
  { packLabel:'Places & Things', xpRequired:240, jp:'くうこう', romaji:'kuukou', en:'airport', kanji:'空港', kanjiDifficulty:'N4' },
  { packLabel:'Places & Things', xpRequired:240, jp:'びょういん', romaji:'byouin', en:'hospital', kanji:'病院', kanjiDifficulty:'N4' },
  { packLabel:'Places & Things', xpRequired:240, jp:'としょかん', romaji:'toshokan', en:'library', kanji:'図書館', kanjiDifficulty:'N4' },
  { packLabel:'Places & Things', xpRequired:240, jp:'コンビニ', romaji:'konbini', en:'convenience store' },
  { packLabel:'Places & Things', xpRequired:240, jp:'こうえん', romaji:'kouen', en:'park', kanji:'公園', kanjiDifficulty:'N4' },
  { packLabel:'Places & Things', xpRequired:240, jp:'ちゅうしゃじょう', romaji:'chuushajou', en:'parking lot', kanji:'駐車場', kanjiDifficulty:'N3' },
  { packLabel:'Places & Things', xpRequired:240, jp:'じはんき', romaji:'jihanki', en:'vending machine', kanji:'自販機', kanjiDifficulty:'N3' },
  { packLabel:'Places & Things', xpRequired:240, jp:'ちか', romaji:'chika', en:'basement / underground', kanji:'地下', kanjiDifficulty:'N4' },
  { packLabel:'Places & Things', xpRequired:240, jp:'おくじょう', romaji:'okujou', en:'rooftop', kanji:'屋上', kanjiDifficulty:'N3' },

  // Unit 3 — Daily Life (verbs tagged with type:'verb')
  { packLabel:'Daily Life', xpRequired:420, type:'verb', jp:'おきます', romaji:'okimasu', en:'wake up', kanji:'起きます', kanjiDifficulty:'N5', tenses:[] },
  { packLabel:'Daily Life', xpRequired:420, type:'verb', jp:'たべます', romaji:'tabemasu', en:'eat', kanji:'食べます', kanjiDifficulty:'N5', tenses:[] },
  { packLabel:'Daily Life', xpRequired:420, type:'verb', jp:'のみます', romaji:'nomimasu', en:'drink', kanji:'飲みます', kanjiDifficulty:'N5', tenses:[] },
  { packLabel:'Daily Life', xpRequired:420, type:'verb', jp:'いきます', romaji:'ikimasu', en:'go', kanji:'行きます', kanjiDifficulty:'N5', tenses:[] },
  { packLabel:'Daily Life', xpRequired:420, type:'verb', jp:'きます', romaji:'kimasu', en:'come', kanji:'来ます', kanjiDifficulty:'N5', tenses:[] },
  { packLabel:'Daily Life', xpRequired:420, type:'verb', jp:'はたらきます', romaji:'hatarakimasu', en:'work', kanji:'働きます', kanjiDifficulty:'N4', tenses:[] },
  { packLabel:'Daily Life', xpRequired:420, type:'verb', jp:'べんきょうします', romaji:'benkyoushimasu', en:'study', kanji:'勉強します', kanjiDifficulty:'N5', tenses:[] },
  { packLabel:'Daily Life', xpRequired:420, type:'verb', jp:'うんどうします', romaji:'undoushimasu', en:'exercise', kanji:'運動します', kanjiDifficulty:'N4', tenses:[] },
  { packLabel:'Daily Life', xpRequired:420, type:'verb', jp:'やすみます', romaji:'yasumimasu', en:'rest / take a break', kanji:'休みます', kanjiDifficulty:'N5', tenses:[] },
  { packLabel:'Daily Life', xpRequired:420, type:'verb', jp:'おわります', romaji:'owarimasu', en:'finish', kanji:'終わります', kanjiDifficulty:'N4', tenses:[] },
  { packLabel:'Daily Life', xpRequired:420, type:'verb', jp:'あるきます', romaji:'arukimasu', en:'walk', kanji:'歩きます', kanjiDifficulty:'N5', tenses:[] },
  { packLabel:'Daily Life', xpRequired:420, jp:'まいにち', romaji:'mainichi', en:'every day', kanji:'毎日', kanjiDifficulty:'N5' },
  { packLabel:'Daily Life', xpRequired:420, jp:'まいばん', romaji:'maiban', en:'every night', kanji:'毎晩', kanjiDifficulty:'N4' },
  { packLabel:'Daily Life', xpRequired:420, jp:'まいつき', romaji:'maitsuki', en:'every month', kanji:'毎月', kanjiDifficulty:'N4' },
  { packLabel:'Daily Life', xpRequired:420, jp:'さいきん', romaji:'saikin', en:'recently / lately', kanji:'最近', kanjiDifficulty:'N4' },
  { packLabel:'Daily Life', xpRequired:420, jp:'しゅうまつ', romaji:'shuumatsu', en:'weekend', kanji:'週末', kanjiDifficulty:'N4' },
  { packLabel:'Daily Life', xpRequired:420, jp:'こんしゅうまつ', romaji:'konshuumatsu', en:'this weekend', kanji:'今週末', kanjiDifficulty:'N4' },

  // Unit 4 — Adjectives & Time
  { packLabel:'Adjectives & Time', xpRequired:620, jp:'さむい', romaji:'samui', en:'cold', kanji:'寒い', kanjiDifficulty:'N5' },
  { packLabel:'Adjectives & Time', xpRequired:620, jp:'さむかった', romaji:'samukatta', en:'was cold', kanji:'寒かった', kanjiDifficulty:'N5' },
  { packLabel:'Adjectives & Time', xpRequired:620, jp:'あつい', romaji:'atsui', en:'hot', kanji:'暑い', kanjiDifficulty:'N4' },
  { packLabel:'Adjectives & Time', xpRequired:620, jp:'あつかった', romaji:'atsukatta', en:'was hot', kanji:'暑かった', kanjiDifficulty:'N4' },
  { packLabel:'Adjectives & Time', xpRequired:620, jp:'おいしい', romaji:'oishii', en:'delicious', kanji:'美味しい', kanjiDifficulty:'N4' },
  { packLabel:'Adjectives & Time', xpRequired:620, jp:'おいしかった', romaji:'oishikatta', en:'was delicious', kanji:'美味しかった', kanjiDifficulty:'N4' },
  { packLabel:'Adjectives & Time', xpRequired:620, jp:'とても', romaji:'totemo', en:'very' },
  { packLabel:'Adjectives & Time', xpRequired:620, jp:'だいたい', romaji:'daitai', en:'about / approximately', kanji:'大体', kanjiDifficulty:'N4' },
  { packLabel:'Adjectives & Time', xpRequired:620, jp:'たんじょうび', romaji:'tanjoubi', en:'birthday', kanji:'誕生日', kanjiDifficulty:'N4' },
  { packLabel:'Adjectives & Time', xpRequired:620, jp:'〜かん', romaji:'~ kan', en:'duration marker (for 1 week = いっしゅうかん)', kanji:'〜間', kanjiDifficulty:'N5' },
  { packLabel:'Adjectives & Time', xpRequired:620, jp:'はなきん', romaji:'hanakin', en:'fun Friday night (start of weekend)', kanji:'華金', kanjiDifficulty:'N1' },

  // Unit 5 — Transport
  { packLabel:'Transport', xpRequired:830, jp:'ひこうき', romaji:'hikouki', en:'airplane', kanji:'飛行機', kanjiDifficulty:'N5' },
  { packLabel:'Transport', xpRequired:830, jp:'ちかてつ', romaji:'chikatetsu', en:'subway / metro', kanji:'地下鉄', kanjiDifficulty:'N4' },
  { packLabel:'Transport', xpRequired:830, jp:'でんしゃ', romaji:'densha', en:'train', kanji:'電車', kanjiDifficulty:'N5' },
  { packLabel:'Transport', xpRequired:830, jp:'バス', romaji:'basu', en:'bus' },
  { packLabel:'Transport', xpRequired:830, jp:'タクシー', romaji:'takushii', en:'taxi' },
  { packLabel:'Transport', xpRequired:830, jp:'ふね', romaji:'fune', en:'ship / boat', kanji:'船', kanjiDifficulty:'N4' },

  // Unit 6 — Restaurant & Food
  { packLabel:'Restaurant & Food', xpRequired:1050, jp:'おすすめ', romaji:'osusume', en:'recommendation', kanji:'お勧め', kanjiDifficulty:'N3' },
  { packLabel:'Restaurant & Food', xpRequired:1050, jp:'おかいけい', romaji:'okaikei', en:'the bill / check', kanji:'お会計', kanjiDifficulty:'N3' },
  { packLabel:'Restaurant & Food', xpRequired:1050, jp:'いらっしゃいませ', romaji:'irasshaimase', en:'welcome (staff greeting)' },
  { packLabel:'Restaurant & Food', xpRequired:1050, jp:'ごちそうさまでした', romaji:'gochisousama deshita', en:'thank you for the meal', kanji:'ご馳走様でした', kanjiDifficulty:'N3' },
  { packLabel:'Restaurant & Food', xpRequired:1050, jp:'いただきます', romaji:'itadakimasu', en:'let\'s eat (before meal)' },
  { packLabel:'Restaurant & Food', xpRequired:1050, jp:'ぶたにく', romaji:'butaniku', en:'pork', kanji:'豚肉', kanjiDifficulty:'N4' },
  { packLabel:'Restaurant & Food', xpRequired:1050, jp:'ぎゅうにく', romaji:'gyuuniku', en:'beef', kanji:'牛肉', kanjiDifficulty:'N4' },
  { packLabel:'Restaurant & Food', xpRequired:1050, jp:'とりにく', romaji:'toriniku', en:'chicken', kanji:'鶏肉', kanjiDifficulty:'N4' },
  { packLabel:'Restaurant & Food', xpRequired:1050, jp:'まぐろ', romaji:'maguro', en:'tuna', kanji:'鮪', kanjiDifficulty:'N1' },
  { packLabel:'Restaurant & Food', xpRequired:1050, jp:'さけ / サーモン', romaji:'sake / saamon', en:'salmon', kanji:'鮭', kanjiDifficulty:'N2' },
  { packLabel:'Restaurant & Food', xpRequired:1050, jp:'えび', romaji:'ebi', en:'shrimp / prawn', kanji:'海老', kanjiDifficulty:'N2' },
  { packLabel:'Restaurant & Food', xpRequired:1050, jp:'ていしょく', romaji:'teishoku', en:'set meal (rice + main + soup)', kanji:'定食', kanjiDifficulty:'N3' },
  { packLabel:'Restaurant & Food', xpRequired:1050, jp:'〜どん', romaji:'~ don', en:'rice bowl with toppings', kanji:'丼', kanjiDifficulty:'N3' },
  { packLabel:'Restaurant & Food', xpRequired:1050, jp:'のみほうだい', romaji:'nomihodai', en:'all-you-can-drink', kanji:'飲み放題', kanjiDifficulty:'N3' },
  { packLabel:'Restaurant & Food', xpRequired:1050, jp:'たべほうだい', romaji:'tabehodai', en:'all-you-can-eat', kanji:'食べ放題', kanjiDifficulty:'N3' },
  { packLabel:'Restaurant & Food', xpRequired:1050, jp:'ハイボール', romaji:'haibooru', en:'highball (whisky + soda)' },
  { packLabel:'Restaurant & Food', xpRequired:1050, jp:'おしぼり', romaji:'oshibori', en:'wet towel given at restaurants', kanji:'お絞り', kanjiDifficulty:'N2' },
]

export const SEED_NUMBERS = [
  // Basic numbers
  { type:'number', category:'basic', number:1,     jp:'いち',   romaji:'ichi',        en:'one',        kanji:'一',    kanjiDifficulty:'N5' },
  { type:'number', category:'basic', number:2,     jp:'に',     romaji:'ni',          en:'two',        kanji:'二',    kanjiDifficulty:'N5' },
  { type:'number', category:'basic', number:3,     jp:'さん',   romaji:'san',         en:'three',      kanji:'三',    kanjiDifficulty:'N5' },
  { type:'number', category:'basic', number:4,     jp:'し / よん', romaji:'shi / yon', en:'four',      kanji:'四',    kanjiDifficulty:'N5' },
  { type:'number', category:'basic', number:5,     jp:'ご',     romaji:'go',          en:'five',       kanji:'五',    kanjiDifficulty:'N5' },
  { type:'number', category:'basic', number:6,     jp:'ろく',   romaji:'roku',        en:'six',        kanji:'六',    kanjiDifficulty:'N5' },
  { type:'number', category:'basic', number:7,     jp:'しち / なな', romaji:'shichi / nana', en:'seven', kanji:'七', kanjiDifficulty:'N5' },
  { type:'number', category:'basic', number:8,     jp:'はち',   romaji:'hachi',       en:'eight',      kanji:'八',    kanjiDifficulty:'N5' },
  { type:'number', category:'basic', number:9,     jp:'きゅう / く', romaji:'kyuu / ku', en:'nine',    kanji:'九',    kanjiDifficulty:'N5' },
  { type:'number', category:'basic', number:10,    jp:'じゅう', romaji:'juu',         en:'ten',        kanji:'十',    kanjiDifficulty:'N5' },
  { type:'number', category:'basic', number:100,   jp:'ひゃく', romaji:'hyaku',       en:'one hundred', kanji:'百',   kanjiDifficulty:'N5' },
  { type:'number', category:'basic', number:1000,  jp:'せん',   romaji:'sen',         en:'one thousand', kanji:'千',  kanjiDifficulty:'N5' },
  { type:'number', category:'basic', number:10000, jp:'まん',   romaji:'man',         en:'ten thousand', kanji:'万',  kanjiDifficulty:'N5' },

  // Minutes 〜分
  { type:'number', category:'counter-minutes', number:1,  jp:'いっぷん',         romaji:'ippun',        en:'1 minute',   kanji:'一分',   kanjiDifficulty:'N5' },
  { type:'number', category:'counter-minutes', number:2,  jp:'にふん',           romaji:'nifun',        en:'2 minutes',  kanji:'二分',   kanjiDifficulty:'N5' },
  { type:'number', category:'counter-minutes', number:3,  jp:'さんぷん',         romaji:'sanpun',       en:'3 minutes',  kanji:'三分',   kanjiDifficulty:'N5' },
  { type:'number', category:'counter-minutes', number:4,  jp:'よんぷん',         romaji:'yonpun',       en:'4 minutes',  kanji:'四分',   kanjiDifficulty:'N5' },
  { type:'number', category:'counter-minutes', number:5,  jp:'ごふん',           romaji:'gofun',        en:'5 minutes',  kanji:'五分',   kanjiDifficulty:'N5' },
  { type:'number', category:'counter-minutes', number:6,  jp:'ろっぷん',         romaji:'roppun',       en:'6 minutes',  kanji:'六分',   kanjiDifficulty:'N5' },
  { type:'number', category:'counter-minutes', number:7,  jp:'ななふん',         romaji:'nanafun',      en:'7 minutes',  kanji:'七分',   kanjiDifficulty:'N5' },
  { type:'number', category:'counter-minutes', number:8,  jp:'はっぷん',         romaji:'happun',       en:'8 minutes',  kanji:'八分',   kanjiDifficulty:'N5' },
  { type:'number', category:'counter-minutes', number:9,  jp:'きゅうふん',       romaji:'kyuufun',      en:'9 minutes',  kanji:'九分',   kanjiDifficulty:'N5' },
  { type:'number', category:'counter-minutes', number:10, jp:'じゅっぷん',       romaji:'juppun',       en:'10 minutes', kanji:'十分',   kanjiDifficulty:'N5' },
  { type:'number', category:'counter-minutes', number:15, jp:'じゅうごふん',     romaji:'juugofun',     en:'15 minutes', kanji:'十五分', kanjiDifficulty:'N5' },
  { type:'number', category:'counter-minutes', number:20, jp:'にじゅっぷん',     romaji:'nijuppun',     en:'20 minutes', kanji:'二十分', kanjiDifficulty:'N5' },
  { type:'number', category:'counter-minutes', number:30, jp:'さんじゅっぷん',   romaji:'sanjuppun',    en:'30 minutes', kanji:'三十分', kanjiDifficulty:'N5' },
  { type:'number', category:'counter-minutes', number:45, jp:'よんじゅうごふん', romaji:'yonjuugofun',  en:'45 minutes', kanji:'四十五分', kanjiDifficulty:'N5' },

  // Hours 〜時 (o'clock)
  { type:'number', category:'counter-hours', number:1,  jp:'いちじ',     romaji:'ichiji',   en:"1 o'clock",  kanji:'一時',   kanjiDifficulty:'N5' },
  { type:'number', category:'counter-hours', number:2,  jp:'にじ',       romaji:'niji',     en:"2 o'clock",  kanji:'二時',   kanjiDifficulty:'N5' },
  { type:'number', category:'counter-hours', number:3,  jp:'さんじ',     romaji:'sanji',    en:"3 o'clock",  kanji:'三時',   kanjiDifficulty:'N5' },
  { type:'number', category:'counter-hours', number:4,  jp:'よじ',       romaji:'yoji',     en:"4 o'clock",  kanji:'四時',   kanjiDifficulty:'N5' },
  { type:'number', category:'counter-hours', number:5,  jp:'ごじ',       romaji:'goji',     en:"5 o'clock",  kanji:'五時',   kanjiDifficulty:'N5' },
  { type:'number', category:'counter-hours', number:6,  jp:'ろくじ',     romaji:'rokuji',   en:"6 o'clock",  kanji:'六時',   kanjiDifficulty:'N5' },
  { type:'number', category:'counter-hours', number:7,  jp:'しちじ',     romaji:'shichiji', en:"7 o'clock",  kanji:'七時',   kanjiDifficulty:'N5' },
  { type:'number', category:'counter-hours', number:8,  jp:'はちじ',     romaji:'hachiji',  en:"8 o'clock",  kanji:'八時',   kanjiDifficulty:'N5' },
  { type:'number', category:'counter-hours', number:9,  jp:'くじ',       romaji:'kuji',     en:"9 o'clock",  kanji:'九時',   kanjiDifficulty:'N5' },
  { type:'number', category:'counter-hours', number:10, jp:'じゅうじ',   romaji:'juuji',    en:"10 o'clock", kanji:'十時',   kanjiDifficulty:'N5' },
  { type:'number', category:'counter-hours', number:11, jp:'じゅういちじ', romaji:'juuichiji', en:"11 o'clock", kanji:'十一時', kanjiDifficulty:'N5' },
  { type:'number', category:'counter-hours', number:12, jp:'じゅうにじ', romaji:'juuniji',  en:"12 o'clock", kanji:'十二時', kanjiDifficulty:'N5' },

  // Calendar days 〜日 (of month)
  { type:'number', category:'calendar-days', number:1,  jp:'ついたち',       romaji:'tsuitachi',    en:'1st',  kanji:'一日',   kanjiDifficulty:'N5' },
  { type:'number', category:'calendar-days', number:2,  jp:'ふつか',         romaji:'futsuka',      en:'2nd',  kanji:'二日',   kanjiDifficulty:'N5' },
  { type:'number', category:'calendar-days', number:3,  jp:'みっか',         romaji:'mikka',        en:'3rd',  kanji:'三日',   kanjiDifficulty:'N5' },
  { type:'number', category:'calendar-days', number:4,  jp:'よっか',         romaji:'yokka',        en:'4th',  kanji:'四日',   kanjiDifficulty:'N5' },
  { type:'number', category:'calendar-days', number:5,  jp:'いつか',         romaji:'itsuka',       en:'5th',  kanji:'五日',   kanjiDifficulty:'N5' },
  { type:'number', category:'calendar-days', number:6,  jp:'むいか',         romaji:'muika',        en:'6th',  kanji:'六日',   kanjiDifficulty:'N5' },
  { type:'number', category:'calendar-days', number:7,  jp:'なのか',         romaji:'nanoka',       en:'7th',  kanji:'七日',   kanjiDifficulty:'N5' },
  { type:'number', category:'calendar-days', number:8,  jp:'ようか',         romaji:'youka',        en:'8th',  kanji:'八日',   kanjiDifficulty:'N5' },
  { type:'number', category:'calendar-days', number:9,  jp:'ここのか',       romaji:'kokonoka',     en:'9th',  kanji:'九日',   kanjiDifficulty:'N5' },
  { type:'number', category:'calendar-days', number:10, jp:'とおか',         romaji:'tooka',        en:'10th', kanji:'十日',   kanjiDifficulty:'N5' },
  { type:'number', category:'calendar-days', number:14, jp:'じゅうよっか',   romaji:'juuyokka',     en:'14th', kanji:'十四日', kanjiDifficulty:'N5' },
  { type:'number', category:'calendar-days', number:20, jp:'はつか',         romaji:'hatsuka',      en:'20th', kanji:'二十日', kanjiDifficulty:'N5' },
  { type:'number', category:'calendar-days', number:24, jp:'にじゅうよっか', romaji:'nijuuyokka',   en:'24th', kanji:'二十四日', kanjiDifficulty:'N5' },

  // Months 〜月
  { type:'number', category:'calendar-months', number:1,  jp:'いちがつ',     romaji:'ichigatsu',   en:'January',   kanji:'一月',   kanjiDifficulty:'N5' },
  { type:'number', category:'calendar-months', number:2,  jp:'にがつ',       romaji:'nigatsu',     en:'February',  kanji:'二月',   kanjiDifficulty:'N5' },
  { type:'number', category:'calendar-months', number:3,  jp:'さんがつ',     romaji:'sangatsu',    en:'March',     kanji:'三月',   kanjiDifficulty:'N5' },
  { type:'number', category:'calendar-months', number:4,  jp:'しがつ',       romaji:'shigatsu',    en:'April',     kanji:'四月',   kanjiDifficulty:'N5' },
  { type:'number', category:'calendar-months', number:5,  jp:'ごがつ',       romaji:'gogatsu',     en:'May',       kanji:'五月',   kanjiDifficulty:'N5' },
  { type:'number', category:'calendar-months', number:6,  jp:'ろくがつ',     romaji:'rokugatsu',   en:'June',      kanji:'六月',   kanjiDifficulty:'N5' },
  { type:'number', category:'calendar-months', number:7,  jp:'しちがつ',     romaji:'shichigatsu', en:'July',      kanji:'七月',   kanjiDifficulty:'N5' },
  { type:'number', category:'calendar-months', number:8,  jp:'はちがつ',     romaji:'hachigatsu',  en:'August',    kanji:'八月',   kanjiDifficulty:'N5' },
  { type:'number', category:'calendar-months', number:9,  jp:'くがつ',       romaji:'kugatsu',     en:'September', kanji:'九月',   kanjiDifficulty:'N5' },
  { type:'number', category:'calendar-months', number:10, jp:'じゅうがつ',   romaji:'juugatsu',    en:'October',   kanji:'十月',   kanjiDifficulty:'N5' },
  { type:'number', category:'calendar-months', number:11, jp:'じゅういちがつ', romaji:'juuichigatsu', en:'November', kanji:'十一月', kanjiDifficulty:'N5' },
  { type:'number', category:'calendar-months', number:12, jp:'じゅうにがつ', romaji:'juunigatsu',  en:'December',  kanji:'十二月', kanjiDifficulty:'N5' },

  // Days of week
  { type:'number', category:'days-of-week', number:1, jp:'げつようび', romaji:'getsuyoubi', en:'Monday',    kanji:'月曜日', kanjiDifficulty:'N5' },
  { type:'number', category:'days-of-week', number:2, jp:'かようび',   romaji:'kayoubi',    en:'Tuesday',   kanji:'火曜日', kanjiDifficulty:'N5' },
  { type:'number', category:'days-of-week', number:3, jp:'すいようび', romaji:'suiyoubi',   en:'Wednesday', kanji:'水曜日', kanjiDifficulty:'N5' },
  { type:'number', category:'days-of-week', number:4, jp:'もくようび', romaji:'mokuyoubi',  en:'Thursday',  kanji:'木曜日', kanjiDifficulty:'N5' },
  { type:'number', category:'days-of-week', number:5, jp:'きんようび', romaji:"kin'youbi",  en:'Friday',    kanji:'金曜日', kanjiDifficulty:'N5' },
  { type:'number', category:'days-of-week', number:6, jp:'どようび',   romaji:'doyoubi',    en:'Saturday',  kanji:'土曜日', kanjiDifficulty:'N5' },
  { type:'number', category:'days-of-week', number:7, jp:'にちようび', romaji:'nichiyoubi', en:'Sunday',    kanji:'日曜日', kanjiDifficulty:'N5' },

  // People counter 〜人
  { type:'number', category:'counter-people', number:1, jp:'ひとり',   romaji:'hitori',   en:'1 person',  kanji:'一人', kanjiDifficulty:'N5' },
  { type:'number', category:'counter-people', number:2, jp:'ふたり',   romaji:'futari',   en:'2 people',  kanji:'二人', kanjiDifficulty:'N5' },
  { type:'number', category:'counter-people', number:3, jp:'さんにん', romaji:'sannin',   en:'3 people',  kanji:'三人', kanjiDifficulty:'N5' },
  { type:'number', category:'counter-people', number:4, jp:'よにん',   romaji:'yonin',    en:'4 people',  kanji:'四人', kanjiDifficulty:'N5' },
  { type:'number', category:'counter-people', number:5, jp:'ごにん',   romaji:'gonin',    en:'5 people',  kanji:'五人', kanjiDifficulty:'N5' },
  { type:'number', category:'counter-people', number:6, jp:'ろくにん', romaji:'rokunin',  en:'6 people',  kanji:'六人', kanjiDifficulty:'N5' },

  // General objects 〜つ (native Japanese counting)
  { type:'number', category:'counter-objects', number:1,  jp:'ひとつ',   romaji:'hitotsu',  en:'1 thing',   kanji:'一つ', kanjiDifficulty:'N5' },
  { type:'number', category:'counter-objects', number:2,  jp:'ふたつ',   romaji:'futatsu',  en:'2 things',  kanji:'二つ', kanjiDifficulty:'N5' },
  { type:'number', category:'counter-objects', number:3,  jp:'みっつ',   romaji:'mittsu',   en:'3 things',  kanji:'三つ', kanjiDifficulty:'N5' },
  { type:'number', category:'counter-objects', number:4,  jp:'よっつ',   romaji:'yottsu',   en:'4 things',  kanji:'四つ', kanjiDifficulty:'N5' },
  { type:'number', category:'counter-objects', number:5,  jp:'いつつ',   romaji:'itsutsu',  en:'5 things',  kanji:'五つ', kanjiDifficulty:'N5' },
  { type:'number', category:'counter-objects', number:6,  jp:'むっつ',   romaji:'muttsu',   en:'6 things',  kanji:'六つ', kanjiDifficulty:'N5' },
  { type:'number', category:'counter-objects', number:7,  jp:'ななつ',   romaji:'nanatsu',  en:'7 things',  kanji:'七つ', kanjiDifficulty:'N5' },
  { type:'number', category:'counter-objects', number:8,  jp:'やっつ',   romaji:'yattsu',   en:'8 things',  kanji:'八つ', kanjiDifficulty:'N5' },
  { type:'number', category:'counter-objects', number:9,  jp:'ここのつ', romaji:'kokonotsu', en:'9 things', kanji:'九つ', kanjiDifficulty:'N5' },
  { type:'number', category:'counter-objects', number:10, jp:'とお',     romaji:'too',       en:'10 things', kanji:'十',  kanjiDifficulty:'N5' },
]

export const SEED_MOMENTS = [
  {
    emoji: '🚃', title: "Tokyo's Train System",
    fact: "Tokyo has 13 subway lines and over 280 stations. The Yamanote Line (山手線) circles the city in about 60 minutes — locals use it like a clock to navigate. Trains run on the second, and missing one by 30 seconds means waiting on the platform. IC cards like Suica make it seamless.",
    vocab: [{ jp:'でんしゃ', romaji:'densha', en:'train' }, { jp:'えき', romaji:'eki', en:'station' }, { jp:'のりかえ', romaji:'norikae', en:'transfer / change trains' }],
  },
  {
    emoji: '🏪', title: 'Convenience Store Culture (コンビニ)',
    fact: "Japanese convenience stores are a world apart. At FamilyMart, Lawson, or 7-Eleven you can pay bills, print documents, get a hot meal, withdraw cash, buy concert tickets, and get surprisingly good coffee — all open 24 hours. The onigiri (おにぎり) section alone is worth a visit.",
    vocab: [{ jp:'コンビニ', romaji:'konbini', en:'convenience store' }, { jp:'おにぎり', romaji:'onigiri', en:'rice ball' }, { jp:'てんいん', romaji:'ten\'in', en:'store clerk' }],
  },
  {
    emoji: '🌸', title: 'Cherry Blossom Season (花見)',
    fact: "Every April, 花見 (hanami — flower viewing) takes over Japan. Friends, families, and coworkers gather under cherry trees to eat, drink, and enjoy together. Parks like Yoyogi and Ueno fill up days in advance with blue tarps saving spots. The season lasts only 1–2 weeks, which makes it feel precious.",
    vocab: [{ jp:'はなみ', romaji:'hanami', en:'flower viewing' }, { jp:'さくら', romaji:'sakura', en:'cherry blossom' }, { jp:'はる', romaji:'haru', en:'spring' }],
  },
  {
    emoji: '🏮', title: 'Before & After Meals',
    fact: "Before eating, Japanese people say いただきます (itadakimasu — 'I humbly receive'). It expresses gratitude to the food, the cook, and the farmer. After finishing: ごちそうさまでした (gochisousama deshita — 'that was a feast'). These are said every single meal, not just on special occasions.",
    vocab: [{ jp:'いただきます', romaji:'itadakimasu', en:'let\'s eat (before meal)' }, { jp:'ごちそうさまでした', romaji:'gochisousama deshita', en:'thank you for the meal' }],
  },
  {
    emoji: '🎌', title: 'The Art of Bowing',
    fact: "Bowing replaces handshakes. A 15° nod works for casual greetings, 30° for sincere thanks, and a deep 45° for apology. Depth and duration signal sincerity. In business settings, people sometimes bow repeatedly in a loop, each trying to show more respect than the other.",
    vocab: [{ jp:'おじぎ', romaji:'ojigi', en:'bow' }, { jp:'よろしくおねがいします', romaji:'yoroshiku onegaishimasu', en:'pleased to meet you / I\'m in your care' }],
  },
  {
    emoji: '🍺', title: 'Izakaya Culture (居酒屋)',
    fact: "An izakaya is the Japanese version of a gastropub — a place to drink, eat small dishes, and unwind with friends or colleagues after work. Otsukaresama (おつかれさまです) is said when meeting there after work. Many offer nomihodai (all-you-can-drink) deals. Golden Gai in Shinjuku has 200+ tiny bars, some fitting only 6 people.",
    vocab: [{ jp:'いざかや', romaji:'izakaya', en:'Japanese pub / gastropub' }, { jp:'かんぱい', romaji:'kanpai', en:'cheers!' }, { jp:'おつかれさまです', romaji:'otsukaresama desu', en:'thank you for your hard work' }],
  },
  {
    emoji: '🎁', title: 'Gift-Giving Culture (おみやげ)',
    fact: "Whenever Japanese people travel, they bring back omiyage — local sweets or snacks — for family, friends, and coworkers. It's not optional; it's expected. Gifts are always presented with both hands and a slight bow. The wrapping is as important as the gift itself. Unwrapping immediately in front of the giver is sometimes considered rude.",
    vocab: [{ jp:'おみやげ', romaji:'omiyage', en:'souvenir / gift from a trip' }, { jp:'ありがとうございます', romaji:'arigatou gozaimasu', en:'thank you very much' }],
  },
  {
    emoji: '🎋', title: 'Fun Friday: はなきん',
    fact: "華金 (hanaきん / hanakin) literally means 'flower Friday' — the feeling of Friday evening after a week of work. It's that TGIF energy, Japanese-style. Izakayas and restaurants are packed. If you're visiting Japan on a Friday evening, expect a very different atmosphere from any other weekday.",
    vocab: [{ jp:'はなきん', romaji:'hanakin', en:'fun Friday night' }, { jp:'きんようび', romaji:'kin\'youbi', en:'Friday' }],
  },
]
